paths:
  /api/products/{query}:
    get:
      summary: Return all products
      tags: 
        - Products
      parameters:
        - name: query
          in: path
          required: false
          description: Query for pagination
          schema:
            type: String
            description: page, limit, category, sort, provider
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: object
                    properties:
                      docs:
                        type: array
                        items:
                          $ref: '#/components/schemas/Product'
                      totalPages:
                        type: integer
                      currentPage:
                        type: integer
                      allCategories:
                        type: array
                        items:
                          type: string
                      allProvider:
                        type: array
                        items:
                          type: string
                      arrayPage:
                        type: array
                        items:
                          type: integer
                      hasPrevPage:
                        type: boolean
                      prevPage:
                        type: integer
                      hasNextPage:
                        type: boolean
                      nextPage:
                        type: integer
        500:
          description: error
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Status500'

  /api/products/{pid}:
    get:
      summary: Return product searched
      tags: 
        - Products
      description: Required session user, premium or admin
      parameters:
        - name: pid
          in: path
          required: true
          description: _id autogenerated by mongo
          schema:
            type: String
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        400:
          description: error
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Status400'
        500:
          description: error
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Status500'

    put:
      summary: Update product
      tags: 
        - Products
      description: Required session, premium(only your products) or admin(all products)
      parameters:
        - name: pid
          in: path
          required: true
          description: _id autogenerated by mongo
          schema:
            type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inputProduct'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status200'
        400:
          description: error
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Status400'
        401:
          description: error
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Status401'
        500:
          description: error
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Status500'

    delete:
      summary: Update product
      tags: 
        - Products
      description: Required session, premium(only your products) or admin(all products)
      parameters:
        - name: pid
          in: path
          required: true
          description: _id autogenerated by mongo
          schema:
            type: String
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status200'
        400:
          description: error
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Status400'
        401:
          description: error
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Status401'
        500:
          description: error
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Status500'

  /api/products:
    post:
      summary: Create product
      tags: 
        - Products
      description: Required session, premium or admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/inputProduct'
      responses:
        200:
          description: success
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        400:
          description: error
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Status400'
        500:
          description: error
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Status500'

  

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerated by Mongo
        title:
          type: String
          description: Title for product, min 3 and max 15 characters
        description:
          type: String
          description: Description for product, min 3 and max 15 characters
        code:
          type: String
          description: Code for product, length 6 characters
        price:
          type: Number
          description: Price for product, value min 0
        status:
          type: Boolean
          description: Status for product, true or false
        stock:
          type: Number
          description: Stock for product, min 1 and max 999
        category:
          type: Number
          description: Category for product
        owner:
          type: String
          description: Owner for product, only USER, PREMIUM or ADMIN
        thumbnails:
          type: Array
          description: Thumbnails for product, no required
      example:
        _id: ObjectId('6434b4043686ffd2f48230c1')
        title: Coca-Cola
        description: Coca-Cola de 330ml retornable(vidrio)
        code: ABC123
        price: 100
        status: true
        stock: 20
        category: drinks
        owner: ADMIN
        thumbnails: https://placehold.co/300x300

    inputProduct:
      type: object
      properties:
        title:
          type: String
          description: Title for product, min 3 and max 15 characters
        description:
          type: String
          description: Description for product, min 3 and max 15 characters
        code:
          type: String
          description: Code for product, length 6 characters
        price:
          type: Number
          description: Price for product, value min 0
        stock:
          type: Number
          description: Stock for product, min 1 and max 999
        category:
          type: Number
          description: Category for product
        thumbnails:
          type: Array
          description: Thumbnails for product, no required
      example:
        title: Coca-Cola
        description: Coca-Cola de 330ml retornable(vidrio)
        code: ABC123
        price: 100
        stock: 20
        category: drinks
        thumbnails: https://placehold.co/300x300

    Status500:
      type: object
      properties:
        status:
          type: String
          description: false
        message:
          type: String
          description: Internal server error
      example:
        status: false
        message: Internal server error

    Status400:
      type: object
      properties:
        Status:
          type: String
          description: success or false
        Message:
          type: String
          description: Message error
      example:
        status: false
        message: Product invalid

    Status401:
      type: object
      properties:
        Status:
          type: String
          description: false
        Message:
          type: String
          description: Message error
      example:
        status: false
        message: No permission

    Status200:
      type: object
      properties:
        Status:
          type: String
          description: success
        Message:
          type: String
          description: Message ok
      example:
        status: false
        message: product deleted or updated